#!/usr/bin/env php
<?php

/**
 * --------------------------------------------------------------------------
 * Launch ConsoleApp                                                        |
 * --------------------------------------------------------------------------
 *
 * Let's call the Console-App from index.php file in the public directory
 */
if (!in_array(PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
    echo 'Warning: The console should be invoked via the CLI version of PHP, not the '.PHP_SAPI.' SAPI'.PHP_EOL;
}

if (!file_exists(BR_PATH . 'vendor/autoload.php') && function_exists('system')) {
    // Before we can even start, we need to run composer first
    if (!function_exists('shell_exec')) {
        throw new RuntimeException('Please do run \'composer install\' to use this application');
    }

    // check for global composer install
    $path = stripos(PHP_OS, 'win') === 0 ? (shell_exec('composer info') !== null ? 'composer' : '') : trim(shell_exec('command -v composer'));

    // fall back to grav bundled composer
    if (!$path || !preg_match('/(composer|composer\.phar)$/', $path)) {
        throw new RuntimeException('Composer not found, please do run \'composer install\' to use this application');
    }

    echo "Preparing to install vendor dependencies...\n\n";
    echo system($path .' --no-interaction -o install');
    echo "\n\n";
}

if (version_compare($ver = PHP_VERSION, $req = '7.2', '<')) {
    exit(sprintf("You are running PHP %s, but Biurad needs at least PHP %s to run.\n", $ver, $req));
}

set_time_limit(0);
@ini_set('default_charset', 'UTF-8');

// Let's intialise console application
require __DIR__ . 'public/index.php';
